#!/usr/bin/perl

use strict;
use warnings;

use lib 'lib';

use RSP;
use RSP::Transaction;
use Mojo::Server::Daemon::Prefork;

my $server = Mojo::Server::Daemon::Prefork->new;
$server->app_class( 'RSP' );
$server->run;
